version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: babichdenis/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend: 
    image: babichdenis/foodgram_frontend
    command: cp -r /app/build/. /app/static/
    volumes: 
      - static:/app/static/

  nginx: 
    image: babichdenis/foodgram_nginx
    ports:
      - 7000:80
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
