version: '3.3'


volumes:
  foodgram_static_volume:
  foodgram_media_volume:
  foodgram_db_volume:


networks:
  default:
    name: foodgram-network

services:

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13
    container_name: foodgram-db
    volumes:
      - foodgram_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: ../backend/foodgram
    restart: always
    volumes:
      - foodgram_static_volume:/app/backend_static/
      - foodgram_media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.3
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_volume:/var/html/backend_static/
      - foodgram_media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

