version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  frontend:
    image: babichdenis/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: babichdenis/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/media
    depends_on:
      - db