version: '3.3'

volumes:
  foodgram_static_volume:
  foodgram_media_volume:
  foodgram_db_volume:
  redoc:


networks:
  default:
    name: foodgram-network

services:

  frontend:
    image: babichdenis/foodgram_frontend:latest
    container_name: foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:15.2-alpine3.17
    container_name: foodgram-db
    volumes:
      - foodgram_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: babichdenis/foodgram_backend:latest
    container_name: foodgram-backend
    restart: always
    volumes:
      - foodgram_static_volume:/app/backend_static/
      - foodgram_media_volume:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: foodgram-nginx
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      #  - ../docs/:/usr/share/nginx/html/api/docs/
      - redoc:/usr/share/nginx/html/api/docs/
      - foodgram_static_volume:/var/html/backend_static/
      - foodgram_media_volume:/var/html/media/
    depends_on:
      - backend
