REGEX = r"^[\w.@+-]+$"
MAX_CHAR_LENGTH = 200
MAX_COLOR_LENGTH = 7
MIN_AMOUNT = 1
MIN_COOKING_TIME = 1
MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
REGEXCOLOR = r"^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
