# Generated by Django 3.2.16 on 2024-01-18 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240118_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritrecipe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
