# Generated by Django 3.2.16 on 2024-01-23 09:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#8b0000', 'red'), ('#ffff00', 'yellow'), ('#006400', 'green')], default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
