# Generated by Django 4.2.8 on 2023-12-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_favorite_favorite_unique_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(
                default=None,
                max_length=2000,
                null=True,
                verbose_name="Описание рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#ffffff",
                max_length=16,
                unique=True,
                verbose_name="Цветовой HEX-код",
            ),
        ),
        migrations.AlterField(
            model_name="tagrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="tagrecipe",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.tag",
                verbose_name="Тег",
            ),
        ),
    ]
