# Generated by Django 4.2.4 on 2023-09-22 10:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_colour_tag_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('color'), name='color_unique'),
        ),
    ]
